import type { NextPage } from 'next'
import Head from 'next/head'
import axios from "axios"
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const [firstName,setFirstName] =useState<string>('')
  const [lastName,setLastName] =useState<string>('')
  const [age,setAge] =useState<number>()
  const [save,setSave]=useState(false)

  const saveUser=async()=>{
    try {
      if(firstName !== "" && lastName!== "" && age !==null){
        console.log(firstName,lastName,age);
        
        const res =await axios.post("http://localhost:5000/user",{firstName,lastName,age}) 
        console.log("res",res.status==201)
        if(res.status==201){
          setSave(true)
          setTimeout(()=>{
            setSave(false)
          },1000)
       }
       console.log("res.data",res.data)
      }
      
    } catch (error) {
      console.log(error);
    }
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <h1>Crud Api</h1>
     <div className={styles.formContainer}>
      <input className={styles.input} name="firstName" value={firstName} onChange={(e)=>setFirstName(e.target.value)} placeholder='Enter Your Firstname'/>
      <input className={styles.input} value={lastName} onChange={(e)=>setLastName(e.target.value)} placeholder='Enter Your Lastname'/>
      <input className={styles.input} value={age} inputMode={'numeric'} onChange={(e)=>setAge(+e.target.value)} placeholder='Enter Your Age'/>
      
      <button onClick={saveUser}  className={styles.btn}>Upload</button>
      {
        save ? <p className={styles.save}>User Saved</p> :null
      }
     </div>
    </div>
  )
}

export default Home
